version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      - aws s3 cp s3://codepipeline-eu-west-2-783384176554/variables/production.env . && cat production.env > /etc/environment && eval $(< production.env)
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - composer install -o --no-interaction
      # - command
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
    - '**/*'
  #discard-paths: no
  #base-directory: location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths