version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t toxaco/generalbaseinfrastructure:php7
  post_build:
    commands:
      - echo Build completed on `date`
