version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      - apt-get update && apt-get install -y awscli
  #pre_build:
    #commands:
      # - command
  build:
    commands:
      # - printenv
      # - aws sts get-caller-identity
      # - aws iam get-user
      # - aws configure
      - aws s3 cp $CURRENT_ENV_PARAMS ./depo_params/
      - ls -al ./depo_params
      - echo $(< "./toDelete/$(ls ./toDelete/)")
      - echo $(< "./depo_params/$(ls ./depo_params/)")
      - eval $(< "./depo_params/$(ls ./depo_params/)") composer install -o --no-interaction
      # - command
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
    - '**/*'
  #discard-paths: no
  #base-directory: location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths