version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      - apt-get update && apt-get install -y awscli
  #pre_build:
    #commands:
      # - command
  build:
    commands:
      # - printenv
      # - aws sts get-caller-identity
      # - aws iam get-user
      # - aws configure
      - aws s3 cp $CURRENT_ENV_PARAMS ./deploy_envs/
      # - aws s3 cp s3://codepipeline-eu-west-2-783384176554/variables/production.env ./deploy_files/
      - cat "./deploy_envs/$(ls ./deploy_envs/)" > /etc/environment
      - cat /etc/environment
      - export TESTING="tested" && echo $TESTING
      - export $(< "./deploy_envs/$(ls ./deploy_envs/)") && echo $SYMFONY__DATABASE__ANOTHER
      # - eval $(< "./deploy_envs/$(ls ./deploy_envs/)") composer install -o --no-interaction
      - export $(< "./deploy_envs/$(ls ./deploy_envs/)") && composer install -o --no-interaction
      # - command
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
    - '**/*'
  #discard-paths: no
  #base-directory: location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
